app:
  name: "go-scraper-engine"
  timeout: 60s

scraper:
  user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  max_depth: 2
  parallelism: 2
  delay: 2s
  max_pages: 5

sites:
  - name: "Nike Etalase (Listing)"
    url: "https://www.nike.com/id/w/mens-shoes-nik1zy7ok"
    selectors:
      container: "[data-testid='product-card__body']"
      title: ".product-card__title"
      price: "[data-testid='product-price']"
      url: "a.product-card__link-overlay"
      pagination: ""

  # - name: "PracticeSite2"
  #   url: "https://www.scrapingcourse.com/ecommerce/"
  #   selectors:
  #     container: "li.product"
  #     title: "h2.woocommerce-loop-product__title"
  #     price: "span.price"
  #     url: "a.woocommerce-LoopProduct-link"
  #     pagination: "a.next"
